config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :events

  resources :categories

  resources :lookbooks

  resources :user_details

  get 'welcome/show'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  root 'welcome#show'

  get 'welcome/stylist_home' => 'welcome#stylist_home'
  get 'welcome/client_home' => 'welcome#client_home'

  get 'user_details/edit' => 'user_details#edit'

  get 'user_details/show' => 'user_details#show'

  get 'user_details/update' => 'user_details#update'

  get 'user_details/index' => 'user_details#index'

  get 'lookbooks/new' => 'lookbooks#new'

  get 'lookbooks/index' => 'lookbooks#index'

  get 'books/index' => 'books#index'

  resources :follows do
    member do
      get :follow
      get :unfollow
      get :list_clients
      get :list_stylists
    end
  end

end

app/models/lookbook.rb
class Lookbook < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_and_belongs_to_many :books
  #Paperclip.options[:command_path] = 'C:/Program Files/ImageMagick-6.9.0-Q16'

  has_attached_file :photo, :styles => { :small => "150x150" , :medium => "250x250"}
  has_attached_file :photo_extra, :styles => { :small => "150x150" , :medium => "250x250"}

  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :photo_extra, :content_type => /\Aimage\/.*\Z/
  #validates_attachment_content_type :photo, :content_type => %w(image/jpeg image/jpg)
  #validates_attachment_content_type :photo_extra, :content_type => %w(image/jpeg image/jpg)
  #validates_attachment_content_type :audio, :content_type => %w(audio/mpeg audio/mp3)

  #validates_attachment_content_type :audio, :content_type => [ 'audio/MP3' ]
  #validates_attachment_size :audio, :less_than => 20.megabytes

  has_attached_file :audio


end

app/controllers/lookbooks_controller.rb
class LookbooksController < ApplicationController
  before_action :set_lookbook, only: [:show, :edit, :update, :destroy, :new, :index]
  respond_to :html, :xml, :json

  def index

    $global_displayTable = 'false';

    if( !params[:book_id].nil? )
      $global_bookID = params[:book_id]
    end

    puts $global_bookID

    if( !$global_bookID.nil? )
      @book = Book.find( $global_bookID )
      @lookbooks = @book.lookbooks
    end

    if( !@lookbooks.nil? )


    if !params[:year].nil? && !params[:event].nil? && !params[:season].nil? && !params[:category].nil? && !params[:stylist_id].nil?

      #All present
    if !params[:year].empty? && !params[:event].empty? && !params[:season].empty? && !params[:category].empty? && !params[:stylist_id].empty?
      @lookbooks = @lookbooks.where(year: params[:year], event: params[:event], season: params[:season], category: params[:category], stylist_id: params[:stylist_id], active: "t")

      #year empty
    elsif params[:year].empty? && !params[:event].empty? && !params[:season].empty? && !params[:category].empty? && !params[:stylist_id].empty?
      @lookbooks = @lookbooks.where(event: params[:event], season: params[:season], category: params[:category], stylist_id: params[:stylist_id], active: "t")

      #event empty
    elsif !params[:year].empty? && params[:event].empty? && !params[:season].empty? && !params[:category].empty? && !params[:stylist_id].empty?
      @lookbooks = @lookbooks.where(year: params[:year], season: params[:season], category: params[:category], stylist_id: params[:stylist_id], active: "t")

      # season empty
    elsif !params[:year].empty? && !params[:event].empty? && params[:season].empty? && !params[:category].empty? && !params[:stylist_id].empty?
        @lookbooks = @lookbooks.where(year: params[:year], event: params[:event], category: params[:category], stylist_id: params[:stylist_id], active: "t")

      # category empty
    elsif !params[:year].empty? && !params[:event].empty? && !params[:season].empty? && params[:category].empty? && !params[:stylist_id].empty?
        @lookbooks = @lookbooks.where(year: params[:year], event: params[:event], season: params[:season], stylist_id: params[:stylist_id], active: "t")

      #stylist_id empty
    elsif !params[:year].empty? && !params[:event].empty? && !params[:season].empty? && !params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( year: params[:year], event: params[:event], season: params[:season], category: params[:category], active: "t" )

      #year and event
    elsif params[:year].empty? && params[:event].empty? && !params[:season].empty? && !params[:category].empty? && !params[:stylist_id].empty?
      @lookbooks = @lookbooks.where(season: params[:season], category: params[:category], stylist_id: params[:stylist_id], active: "t")

      #year and season
    elsif params[:year].empty? && !params[:event].empty? && params[:season].empty? && !params[:category].empty? && !params[:stylist_id].empty?
      @lookbooks = @lookbooks.where(event: params[:event], category: params[:category], stylist_id: params[:stylist_id], active: "t")

      #year and Category
    elsif params[:year].empty? && !params[:event].empty? && !params[:season].empty? && params[:category].empty? && !params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( event: params[:event], season: params[:season], stylist_id: params[:stylist_id], active: "t")

    #season and category
    elsif !params[:year].empty? && !params[:event].empty? && params[:season].empty? && params[:category].empty? && !params[:stylist_id].empty?
      @lookbooks = @lookbooks.where(year: params[:year], event: params[:event], stylist_id: params[:stylist_id], active: "t")

    #season and event
    elsif !params[:year].empty? && params[:event].empty? && params[:season].empty? && !params[:category].empty? && !params[:stylist_id].empty?
      @lookbooks = @lookbooks.where(year: params[:year], category: params[:category], stylist_id: params[:stylist_id], active: "t")

    #Category and event
    elsif !params[:year].empty? && params[:event].empty? && !params[:season].empty? && params[:category].empty? && !params[:stylist_id].empty?
      @lookbooks = @lookbooks.where(year: params[:year], season: params[:season], stylist_id: params[:stylist_id], active: "t")

      # year, season, category empty
    elsif params[:year].empty? && !params[:event].empty? && params[:season].empty? && params[:category].empty? && !params[:stylist_id].empty?
        @lookbooks = @lookbooks.where(event: params[:event], stylist_id: params[:stylist_id], active: "t")

        # year, season, event empty
    elsif params[:year].empty? && params[:event].empty? && params[:season].empty? && !params[:category].empty? && !params[:stylist_id].empty?
          @lookbooks = @lookbooks.where(category: params[:category], stylist_id: params[:stylist_id], active: "t")

          # event, season, category empty
    elsif !params[:year].empty? && params[:event].empty? && params[:season].empty? && params[:category].empty? && !params[:stylist_id].empty?
            @lookbooks = @lookbooks.where(year: params[:year], stylist_id: params[:stylist_id], active: "t")

            # year, event, category empty
    elsif params[:year].empty? && params[:event].empty? && !params[:season].empty? && params[:category].empty? && !params[:stylist_id].empty?
              @lookbooks = @lookbooks.where(season: params[:season], stylist_id: params[:stylist_id], active: "t")

      #event and Stylist empty
    elsif !params[:year].empty? && params[:event].empty? && !params[:season].empty? && !params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where(year: params[:year], season: params[:season], category: params[:category], active: "t")

      #Category and Stylist empty
    elsif !params[:year].empty? && !params[:event].empty? && !params[:season].empty? && params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where(year: params[:year], season: params[:season], event: params[:event], active: "t" )

      #Season and Stylist empty
    elsif !params[:year].empty? && !params[:event].empty? && params[:season].empty? && !params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where(year: params[:year], event: params[:event], category: params[:category], active: "t" )

      #Year and Stylist empty
    elsif params[:year].empty? && !params[:event].empty? && !params[:season].empty? && !params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( event: params[:event], category: params[:category], season: params[:season], active: "t" )

      #Category, event, stylist empty
    elsif !params[:year].empty? && params[:event].empty? && !params[:season].empty? && params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( year: params[:year], season: params[:season], active: "t" )

      #Season, event, stylist empty
    elsif !params[:year].empty? && params[:event].empty? && params[:season].empty? && !params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( year: params[:year], category: params[:category], active: "t" )

      #Year, event, stylist empty
    elsif params[:year].empty? && params[:event].empty? && !params[:season].empty? && !params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( category: params[:category], season: params[:season], active: "t" )

      #Season, Year, stylist empty
    elsif params[:year].empty? && !params[:event].empty? && params[:season].empty? && !params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( category: params[:category], event: params[:event], active: "t" )

      #Season, Category, stylist empty
    elsif !params[:year].empty? && !params[:event].empty? && params[:season].empty? && params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( year: params[:year], event: params[:event], active: "t" )

      #Category, Year, stylist empty
    elsif params[:year].empty? && !params[:event].empty? && !params[:season].empty? && params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( season: params[:season], event: params[:event], active: "t" )

      #Year, Season, Event, Stylist empty
    elsif params[:year].empty? && params[:event].empty? && params[:season].empty? && !params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( category: params[:category], active: "t" )

      #Year, Category, Event, Stylist empty
    elsif params[:year].empty? && params[:event].empty? && !params[:season].empty? && params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( season: params[:season], active: "t" )

      #Year, Season, Category, Stylist empty
    elsif params[:year].empty? && !params[:event].empty? && params[:season].empty? && params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( event: params[:event], active: "t" )

      #Season, Category, Event, Stylist empty
    elsif !params[:year].empty? && params[:event].empty? && params[:season].empty? && params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( year: params[:year], active: "t" )

      #Season, Category, Event, year empty
    elsif params[:year].empty? && params[:event].empty? && params[:season].empty? && params[:category].empty? && !params[:stylist_id].empty?
      @lookbooks = @lookbooks.where( stylist_id: params[:stylist_id], active: "t" )

    else
      @lookbooks = @book.lookbooks
    end

    if params[:year].empty? && params[:event].empty? && params[:season].empty? && params[:category].empty? && params[:stylist_id].empty?
      @lookbooks = @lookbooks.where(active: "t")
    end

    else

app/helpers/lookbooks_helper.rb
module LookbooksHelper
end

app/views/lookbooks/_form.html.erb
<script>
    $(document).ready(function(){

        $('#CategoryForm').hide(); //Initially form wil be hidden.
        $('#EventForm').hide();
        $('#BookForm').hide();
        $('#BookDiv').hide();
        $('#EventDiv').hide();
        $('#CategoryDiv').hide();

        $('#CategoryButton').click(function() {
            $('#CategoryForm').show();//Form shows on button click

            $('#CategoryDiv').show();

            $("html, body").animate({ scrollTop: $(document).height() }, "slow");
            document.getElementById('CatNameID').focus();

        });

        $('#EventButton').click(function() {
            $('#EventForm').show();//Form shows on button click

            $('#EventDiv').show();

            $("html, body").animate({ scrollTop: $(document).height() }, "slow");
            document.getElementById('EventNameID').focus();
        });

        $('#BookButton').click(function() {
            $('#BookForm').show();//Form shows on button click\
            $('#BookDiv').show();

            $("html, body").animate({ scrollTop: $(document).height() }, "slow");
            document.getElementById('BookNameID').focus();
        });

    });


    function report(value) {

        document.getElementById('bookidfield').value=value;
    }


    function validateMyForm()
    {

        if ( document.getElementById('bookDropDown').value ==  "")  {

            alert("You must select a Book");
            document.getElementById('bookDropDown').focus();
            return false;
        }

        return true;
    }

    function validateCategoryForm()
    {
        var catNameID = document.getElementById("CatNameID").value;

        if( catNameID == "")
        {
            alert("Category cannot be empty!");
            document.getElementById('CatNameID').focus();
            return false
        }

        <%
         @all_cate = Category.all
         @all_cate.each do |cat| %>

            if(catNameID == "<%= cat.name %>" )
            {
                alert("Category "+ "<%= cat.name %>" + " already exists!");
                document.getElementById('CatNameID').value = "";
                document.getElementById('CatNameID').focus();
                return false;
            }
        <%end %>

        return true;
    }

    function validateBookForm()
    {
        var bookNameID = document.getElementById("BookNameID").value;

        if( bookNameID == "")
        {
            alert("Book cannot be empty!");
            document.getElementById('BookNameID').focus();
            return false
        }

        <%
         @all_books = Book.all
         @all_books.each do |book| %>

        if(bookNameID == "<%= book.name %>" )
        {
            alert("Book "+ "<%= book.name %>" + " already exists!");
            document.getElementById('BookNameID').value = "";
            document.getElementById('BookNameID').focus();
            return false;
        }
        <%end %>

        return true;
    }

    function validateEventForm()
    {
        var eventNameID = document.getElementById("EventNameID").value;

        if( eventNameID == "")
        {
            alert("Event cannot be empty!");
            document.getElementById('EventNameID').focus();
            return false
        }

        <%
         @all_events = Event.all
         @all_events.each do |eve| %>

        if(eventNameID == "<%= eve.name %>" )
        {
            alert("Event "+ "<%= eve.name %>" + " already exists!");
            document.getElementById('EventNameID').value = "";
            document.getElementById('EventNameID').focus();
            return false;
        }
        <%end %>

        return true;
    }


</script>

<%= form_for(@lookbook, :html => { :multipart => true} ) do |f| %>
  <% if @lookbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lookbook.errors.count, "error") %> prohibited this lookbook from being saved:</h2>

      <ul>
      <% @lookbook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" >
    <%= f.label :user_id %><br>
    <%= $global_lookbookid %>
  </div>

    <% if( $global_current_book.nil? )%>

    <div class="field">

      <%= f.label :book_id %><br>

      <select onchange="report(this.value)" name="bookDropDown" id="bookDropDown">

        <option value="" ></option>

        <%
           @all_books = Book.all
        %>

        <%  @all_books.each do |book_record|

          #if( !book_record.stylist_id.nil?)

          if( book_record.stylist_id == current_user.id.to_s &&  book_record.client_id == $global_lookbookid.to_s)

        %>
                <option value="<%= book_record.id %>" ><%= book_record.name  %></option>
            <%
               # end
               end
               end %>


      </select>

      <button type="button" id="BookButton" class="glyphicon glyphicon-plus"></button>

      <br>


    </div>
    <%else
        @current_b = Book.find_by_name( $global_current_book );

        $global_bookid = @current_b.id;
        puts $global_bookid;
    %>
        <div class="field" >
          <%= f.label :Book_Name %><br>
          <%= $global_current_book %>
        </div>

    <% end %>

  <div class="field">
    <%= f.label :season %><br>

    <select <%= f.text_field :season %> >

      <% if  @lookbook.season == "Spring" %>
          <option value="Spring" selected>Spring</option>
      <%else%>
          <option value="Spring">Spring</option>
      <%end%>

      <% if  @lookbook.season == "Summer" %>
          <option value="Summer" selected>Summer</option>
      <%else%>
          <option value="Summer">Summer</option>
      <%end%>

      <% if  @lookbook.season == "Autumn" %>
          <option value="Autumn" selected>Autumn</option>
      <%else%>
          <option value="Autumn">Autumn</option>
      <%end%>

      <% if  @lookbook.season == "Winter" %>
          <option value="Winter" selected>Winter</option>
      <%else%>
          <option value="Winter">Winter</option>
      <%end%>

    </select>
  </div>
  <div class="field">
    <%= f.label :category %><br>

    <select <%= f.text_field :category %> id="CatList" name="CatList">

      <%
         @all_categories = Category.all
      %>

      <%  @all_categories.each do |cat_record| %>

          <% if ( @lookbook.category == cat_record.name ) %>
              <option value="<%= cat_record.name %>" selected><%= cat_record.name  %> </option>
          <%else%>
              <option value="<%= cat_record.name %>"><%= cat_record.name  %> </option>
          <%end%>

          <%end %>


    </select>

    <button type="button" id="CategoryButton" class="glyphicon glyphicon-plus"></button>


    <!--<%= link_to 'New Category', new_category_path, :onclick=>"window.open(this.href,'create_company', 'height=600, width=600');return false"%>-->
    <br>


  </div>
  <div class="field">
    <%= f.label :event %><br>
    <select <%= f.text_field :event %>>

      <%
         @all_events = Event.all
      %>

      <%  @all_events.each do |event_record|

        if( @lookbook.event == event_record.name )
      %>
          <option value="<%= event_record.name %>" selected><%= event_record.name  %> </option>

          <%else%>
              <option value="<%= event_record.name %>"><%= event_record.name  %> </option>
          <%end%>

    <%end %>


    </select>

    <button type="button" id="EventButton"  class="glyphicon glyphicon-plus"></button>

    <!--<%= link_to 'New Event', new_event_path %>-->
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :look %><br>
    <%= f.text_field :look %>
    <%= f.text_field :look_2 %>
    <%= f.text_field :look_3 %>
    <%= f.text_field :look_4 %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>

    <div class="field">
      <%= f.label :Outfit %><br>
      <%= f.file_field :photo %><br>
    </div>

    <div class="field">
      <%= f.label :Additional_Photo %><br>
      <%= f.file_field :photo_extra %><br>
    </div>

    <div class="field">
      <%= f.label :Audio %><br>
      <%= f.file_field :audio %><br>
    </div>

    <%= f.hidden_field :user_id, :value => $global_lookbookid %>

    <%= f.hidden_field :active, :value => true %>
    <%= f.hidden_field :book_id, :id => "bookidfield", :value => $global_bookid %>

    <%= if current_user.has_role? :stylist
        f.hidden_field :stylist_id, :value => current_user.id
    end
    %>

  <div class="actions">
    <%= f.submit  :onclick => "return validateMyForm();"  %>
  </div>
<% end %>

<br/>

<div id="CategoryDiv" name="CategoryDiv" style="border:1px solid red">

<%= form_for @category,:html => {:id => "CategoryForm"} do |c| %>

    <%= c.text_field :name, :id => "CatNameID"%>
      <%= c.submit  :onclick => "return validateCategoryForm();"  %>
<% end -%>

</div>

<div id="EventDiv" name="EventDiv" style="border:1px solid blue">

<%= form_for @event,:html => {:id => "EventForm"} do |e| %>

    <%= e.text_field :name, :id => "EventNameID"%>
      <%= e.submit  :onclick => "return validateEventForm();"  %>
<% end -%>

  </div>

<div id="BookDiv" name="BookDiv" style="border:1px solid yellow">

<%= form_for @book,:html => {:id => "BookForm"} do |b| %>

    <%= b.hidden_field :stylist_id, :value => current_user.id %>
    <%= b.hidden_field :client_id, :value => $global_lookbookid %>
      <%= b.hidden_field :active, :value => false %>
    <%= b.text_field :name, :id => "BookNameID"%>
      <%= b.submit  :onclick => "return validateBookForm();"  %>
<% end -%>

</div>

app/views/lookbooks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <h1 class="text-center login-title">Editing Page</h1>
      <div class="account-wall">

<%= render 'form' %>

<%= link_to 'Show', @lookbook %> |
<%= link_to 'Back', lookbooks_path %>

</div>
</div>
</div>
</div>

app/views/lookbooks/index.html.erb
<script>

    window.onload = function () {

        //$("#inactive").hide();
        //$('td:nth-child(1),th:nth-child(1)').hide();

        //var checkbox = document.getElementById("show_inactives");

        //checkbox.onclick = function () {

        //}
        /*
        checkbox.onchange = function () {
            if (this.checked) {
                $("#inactive").show();
                $('td:nth-child(1),th:nth-child(1)').show();

            }
            else {
                $("#inactive").hide();
                $('td:nth-child(1),th:nth-child(1)').hide();
            }

        };*/
    };

</script>
<br>
<!--<h1 class="text-center login-title">Lookbooks</h1>-->

<div class="text-center login-title"> <%=image_tag("logo.png", height: '140', width: '160')%> </div>

<!--<%= image_tag("logo.png") %>-->
<div class="container">
  <div class="well col-xs-8 col-sm-8 col-md-8 col-lg-8 col-xs-offset-2 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">
    <div class="row user-row">


      <%
         if current_user.has_role? :client

      %>

          <% if( !@lookbooks.nil? ) %>
          <% @lookbooks.each do |lookbook| %>
              <% if current_user.id == lookbook.user_id %>

                  <div align="center" style = "border:1px solid black;">


                    <a href="<%= lookbook_path(lookbook) %>">
                    <img class="small" src="<%=lookbook.photo.url%>" width="200"/><br>
                    </a>

                    <%= lookbook.season %><br>
                    <%= lookbook.category %><br>
                    <%= lookbook.event %><br>
                    <%= lookbook.description %><br>
                    <%= lookbook.look %><br>
                    <%= lookbook.created_at %><br>

                  </div>
                  <br>

              <%end%>
              <%end%>
          <% end %>


      <%

         end


         if current_user.has_role? :stylist

      %>

          <% if( !@lookbooks.nil? ) %>
          <% @lookbooks.each do |lookbook| %>

              <div align="center" style = "border:1px solid black;">

                <a href="<%= lookbook_path(lookbook) %>">
                  <img class="small" src="<%=lookbook.photo.url%>" width="200"/><br>
                </a>

                <%= lookbook.season %><br>
                <%= lookbook.category %><br>
                <%= lookbook.event %><br>
                <%= lookbook.description %><br>
                <%= lookbook.look %><br>
                <%= lookbook.created_at %><br>
                <!--<%= link_to 'Edit', edit_lookbook_path(lookbook, :type => lookbook.user_id ) %><br>-->
                <!--<%= link_to 'Destroy', lookbook, method: :delete, data: { confirm: 'Are you sure?' } %><br>-->

              </div>

          <% end %>
          <% end %>
      <%
         end
      %>

      <br>
      <!--<%= link_to "Back", :back %>-->
      <%= link_to '', welcome_show_path, class: "glyphicon glyphicon-home"%>

    </div>

  </div>
</div>



<!--<%= link_to 'New Lookbook', new_lookbook_path %>-->

app/views/lookbooks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <h1 class="text-center login-title">New Page</h1>
      <div class="account-wall">

<%= render 'form' %>

<%= link_to "Back", :back %>

      </div>
    </div>
  </div>
</div>

app/views/lookbooks/show.html.erb
<!--<h1 class="text-center login-title">Lookbook</h1>-->

<div class="text-center login-title"> <%=image_tag("logo.png", height: '140', width: '160')%> </div>

<%
   @userDetails = UserDetail.find_by_user_id(@lookbook.user_id);

%>
<h1 class="text-center login-title"> <%= @userDetails.first_name %>  <%= @userDetails.last_name %> </h1>
<%

%>


<div class="container">
  <div class="well col-xs-8 col-sm-8 col-md-8 col-lg-8 col-xs-offset-2 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">
    <div class="row user-row">

<p id="notice"><%= notice %></p>

<!--<p>
  <strong>User:</strong>
  <%= @lookbook.user_id %>
</p>
-->

      <%
         @lookbook.books.each do |p|
           $book_name =  p.name
         end %>

<table align="center">
  <tr>
    <td><b>Date:</b></td>
    <td><%= @lookbook.created_at %></td>
    <td></td>
  </tr>
  <%if @lookbook.books.exists?%>
  <tr>
    <td><b>Part of book:</b></td>
    <td><%=$book_name%>
    </td>
    <td></td>
  </tr>
      <%end%>
  <tr>
    <td><b>Category:</b></td>
    <td><%= @lookbook.category %></td>
    <td rowspan="9">

      <!-- Lets make a simple image magnifier -->
      <div class="magnify">

        <!-- This is the magnifying glass which will contain the original/large version -->
        <div class="large"></div>

        <!-- This is the small image -->
        <img class="small" src="<%=@lookbook.photo.url%>" width="200"/>

      </div>

    </td>
  </tr>
  <tr>
    <td><b>Season:</b></td>
    <td><%= @lookbook.season %></td>
    <td rowspan="9">
      <%
          if @lookbook.photo_extra.exists?
      %>
          <!-- Lets make a simple image magnifier -->
          <div class="magnify_two">

            <!-- This is the magnifying glass which will contain the original/large version -->
            <div class="large_two"></div>

            <!-- This is the small image -->
            <img class="small_two" src="<%=@lookbook.photo_extra.url%>" width="200"/>

          </div>
      <%
          end
      %>
    </td>
  </tr>
  <tr>
    <td><b>Event:</b></td>
    <td><%= @lookbook.event %></td>
    <td></td>
  </tr>
  <tr>
    <td><b>Description:</b></td>
    <td><%= @lookbook.description %></td>
    <td></td>
  </tr>
  <tr>
  <td><b>Look:</b></td>
  <td><%= @lookbook.look %></td>
  <td></td>
</tr>
  <tr>
    <td></td>
    <td><%= @lookbook.look_2 %></td>
    <td rowspan="9">
      <%=
        if @lookbook.audio.exists?
          link_to('Listen to Audio Clip', @lookbook.audio.url)
        end
    %> </td>
  </tr>
  <tr>
    <td></td>
    <td><%= @lookbook.look_3 %></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><%= @lookbook.look_4 %></td>
    <td></td>
  </tr>

</table>





<%
   if current_user.has_role? :client
%>



    <%= link_to 'Back', lookbooks_path %>
   <!-- <%= link_to 'Edit', edit_lookbook_path(@lookbook) %> -->
<%
   end

%>

<%
   if current_user.has_role? :stylist

%>
          <%= link_to 'Edit', edit_lookbook_path(@lookbook, :type => @lookbook.user_id, :current_book_name => $book_name ) %>

          |
          <%= link_to 'Delete', @lookbook, method: :delete, data: { confirm: 'Are you sure?' } %>
          |
<!-- <%= link_to 'Back', lookbooks_path %> -->
<%= link_to 'Upload Another Page', new_lookbook_path(:type => @lookbook.user_id, :current_book_name => $book_name)  %> |

    <%= link_to 'Client List', list_clients_follow_path(current_user.id)  %>

<%
   end

%>

    </div>
  </div>
</div>
</div>