config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :events

  resources :categories

  resources :lookbooks

  resources :user_details

  get 'welcome/show'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  root 'welcome#show'

  get 'welcome/stylist_home' => 'welcome#stylist_home'
  get 'welcome/client_home' => 'welcome#client_home'

  get 'user_details/edit' => 'user_details#edit'

  get 'user_details/show' => 'user_details#show'

  get 'user_details/update' => 'user_details#update'

  get 'user_details/index' => 'user_details#index'

  get 'lookbooks/new' => 'lookbooks#new'

  get 'lookbooks/index' => 'lookbooks#index'

  get 'books/index' => 'books#index'

  resources :follows do
    member do
      get :follow
      get :unfollow
      get :list_clients
      get :list_stylists
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def show
    puts 'Welcome Method';
    #check here if its going to redirect to the right screen
    # redirect_to '/welcome/stylist_home'

    @follow = Follow.new
    if current_user.has_role? :stylist
        puts 'Stylist, redirect'
        redirect_to '/welcome/stylist_home'
    else if current_user.has_role? :client
           puts 'Client, redirect'
           redirect_to '/welcome/client_home'

      end
    end




  end

  def stylist_home
    puts 'Welcome Stylist';
  end

  def client_home
    puts 'Welcome Stylist';

  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/client_home.html.erb
<% if user_signed_in? %>

    <%
        @UserSignedInDetails = UserDetail.find_by_user_id(current_user.id);


    %>

    <%
       if !@UserSignedInDetails.nil?
    %>
      <h1 align="center">Welcome <%= @UserSignedInDetails.first_name %> </h1>
        <%
          end
        %>

      <div style="text-align:center">
      <%= link_to "Profile", {:action=>"show",  :controller => "user_details"} %> |

      <!--<%= link_to "List of Stylists", list_stylists_follow_path(current_user.id)%> -->

      <!--<%= link_to "Lookbooks", lookbooks_path %>-->

        <%= link_to "Lookbooks", books_path %>

        </div>

<% end %>

app/views/welcome/show.html.erb
<% if user_signed_in? %>

    <h1 align="center">Welcome Administrator</h1>

    <div style="text-align:center">
      <%= link_to "Create User", {:action=>"new",  :controller => "users/registrations"} %> |
      <%= link_to "Edit Users", {:action=>"index",  :controller => "user_details"} %>
</div>


      <div align="center" class="panel-body"> <b>Link a Client to a Stylist... </b></div>

      <div align="center" class="panel-body">

        <%
            @all_users = User.all
        %>

        <script>
            function show_alert()
            {
                alert("Link Created!");
            }
        </script>

      <%= form_for @follow do |f| -%>

            <b>Client ID:</b>

            <select <%= text_field_tag "client_id" %> >
              <option value=""> </option>
              <%  @all_users.each do |user_record|

                if user_record.has_role? :client

                  if UserDetail.where(:user_id => user_record.id).blank?
                    # no user details record for this id
                  else
                    @user_detail = UserDetail.find_by_user_id(user_record.id)

                    if !@user_detail.first_name.nil? && !@user_detail.last_name.nil? %>
                              <option value="<%= user_record.id %>"><%= @user_detail.first_name  %> <%= @user_detail.last_name %> </option>
                          <%end

                  end

              %>

                  <%end

                    end %>
            </select>

            <b>Stylist ID:</b>

            <select <%= text_field_tag "stylist_id" %> >
              <option value=""> </option>
              <%  @all_users.each do |user_record|

                if user_record.has_role? :stylist

              %>
                      <option value="<%= user_record.id %>"><%= user_record.email %></option>
                  <%end

                    end %>
            </select>


            <%= f.submit :onclick => "return confirm('Creating Link!')"  %>
        <% end -%>

      </div>





<% end %>

app/views/welcome/stylist_home.html.erb
<% if user_signed_in? %>

      <h1 align="center">Welcome <%= current_user.email %> </h1>

      <div style="text-align:center">
      <%= link_to "List of Clients", list_clients_follow_path(current_user.id), align:"center"%>
        </div>

<% end %>