config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :events

  resources :categories

  resources :lookbooks

  resources :user_details

  get 'welcome/show'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  root 'welcome#show'

  get 'welcome/stylist_home' => 'welcome#stylist_home'
  get 'welcome/client_home' => 'welcome#client_home'

  get 'user_details/edit' => 'user_details#edit'

  get 'user_details/show' => 'user_details#show'

  get 'user_details/update' => 'user_details#update'

  get 'user_details/index' => 'user_details#index'

  get 'lookbooks/new' => 'lookbooks#new'

  get 'lookbooks/index' => 'lookbooks#index'

  get 'books/index' => 'books#index'

  resources :follows do
    member do
      get :follow
      get :unfollow
      get :list_clients
      get :list_stylists
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base

  has_and_belongs_to_many :lookbooks


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json

  def index

    if !params[:id].nil?
      $global_currentClientSearchID = params[:id]
    end

    @books = Book.all

    respond_with(@books)
  end

  def show
    #respond_with(@book)
    redirect_to :back
  end

  def new
    @book = Book.new
    respond_with(@book)
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to :back
  end

  def update
    @book.update(book_params)
    respond_with(@book)
  end

  def destroy

    @lookbooks = @book.lookbooks

    @lookbooks.each do |l|
      l.delete
    end

    @book.lookbooks.clear

    @book.destroy
    respond_with(@book)

  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      #params.require(:book).permit(:name)
      params.require(:book).permit!
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <%= f.hidden_field :active, :value => false %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @book %> |-->
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="text-center login-title"> <%=image_tag("logo.png", height: '140', width: '160')%> </div>

<div class="container">
  <div class="well col-xs-8 col-sm-8 col-md-8 col-lg-8 col-xs-offset-2 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">
    <div class="row user-row">
      <h1 align="center">LookBooks</h1>
<table>
  <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book|

      if (!$global_currentClientSearchID.nil?)

          @c_user =   $global_currentClientSearchID;
        else
          @c_user =   current_user.id;
      end

        if (book.client_id == @c_user)
    %>

        <% if current_user.has_role? :client %>


              <% if book.active == true %>


          <tr>

        <%
           @lookbooks = book.lookbooks
           @lookbooks = @lookbooks.first

           if( !@lookbooks.nil? )
           puts @lookbooks.id;
        %>

        <td>

          <a href="<%= lookbooks_path(book_id: book.id) %>">
          <img class="small" src="<%=@lookbooks.photo.url%>" width="200"/>
          </a>

          <% end%>

        <!--<td><%= link_to 'Show', book %></td>-->
       <!-- <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->

        <td><%= book.name %></td>


      </tr> <%end%>
        <%else%>


              <tr>

                <%
                   @lookbooks = book.lookbooks
                   @lookbooks = @lookbooks.first
                   if( !@lookbooks.nil? )
                     puts @lookbooks.id;
                %>

                <td>

                  <a href="<%= lookbooks_path(book_id: book.id) %>">
                    <img class="small" src="<%=@lookbooks.photo.url%>" width="200"/>
                  </a>
                <% end%>
                <td><%= book.name %></td>


                <td>

                      <%
                         if book.active == true
                      %>

                          <%= form_for book do |f| -%>

                              <%= f.hidden_field :id, :value => book.id %>
                              <%= f.hidden_field :active, :value => false %>
                              <%= f.submit "Set to Inactive"%>
                          <% end -%>

                      <% else %>

                          <%= form_for book do |f| -%>

                              <%= f.hidden_field :id, :value => book.id %>
                              <%= f.hidden_field :active, :value => true %>
                              <%= f.submit "Set to Active"%>
                          <% end -%>


                      <%end%>

                    <td><%= link_to 'Edit', edit_book_path(book) %> |</td>
                    <td> <%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' } %> |</td>

                    <% if( !@lookbooks.nil? ) %>
                    <td> <%= link_to 'Upload Another Page', new_lookbook_path(:type => @lookbooks.user_id, :current_book_name => book.name )  %></td>
                    <%else%>
                    <td> <%= link_to 'Upload Another Page', new_lookbook_path(:type => book.client_id, :current_book_name => book.name )  %></td>
                    <%end%>

                </td>
              </tr>



        <%end%>

    <% end
    end%>
  </tbody>
</table>

<br>
<!--<%= link_to 'New Book', new_book_path %>-->
    </div>

  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>