config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :events

  resources :categories

  resources :lookbooks

  resources :user_details

  get 'welcome/show'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  root 'welcome#show'

  get 'welcome/stylist_home' => 'welcome#stylist_home'
  get 'welcome/client_home' => 'welcome#client_home'

  get 'user_details/edit' => 'user_details#edit'

  get 'user_details/show' => 'user_details#show'

  get 'user_details/update' => 'user_details#update'

  get 'user_details/index' => 'user_details#index'

  get 'lookbooks/new' => 'lookbooks#new'

  get 'lookbooks/index' => 'lookbooks#index'

  get 'books/index' => 'books#index'

  resources :follows do
    member do
      get :follow
      get :unfollow
      get :list_clients
      get :list_stylists
    end
  end

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def follow
    #@user = User.find(params[:id])
    #current_user.follow(@user)
    @user_details = UserDetail.find(params[:id])
    @user = User.find( @user_details.user_id )
    current_user.follow(@user);
  end

  def unfollow
    #@user = User.find(params[:user_id])
    @user_details = UserDetail.find(params[:id])
    @user = User.find( @user_details.user_id )
    current_user.stop_following(@user)
  end


  def list_clients
  #The records that an user (Stylist) is following (Clients)
  end


  def list_stylists
   #Number of followers of a user (Client) by different stylists
  end

  def create
    puts 'Create link between users...'

    if !params["client_id"].empty? && !params["stylist_id"].empty?

      @client_user = User.find( params["client_id"] )
      @stylist_user = User.find( params["stylist_id"] )

      @client_user.follow(@stylist_user);

    end

    redirect_to '/welcome/show'

  end

end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/list_clients.erb
<!--The records that an user (Stylist) is following (Clients)-->

<br>
<h1 class="text-center login-title">List of Clients (<%=current_user.followers_count%>)</h1>
<div class="container">
  <div class="well col-xs-8 col-sm-8 col-md-8 col-lg-8 col-xs-offset-2 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">
    <div class="row user-row">
      <table>
        <thead>

        <%  @user_list = current_user.user_followers;
        %>

        <% @user_list.each do | clients | %>

            <%
               @user_detail = UserDetail.find_by_user_id(clients.id)
            %>

            <tr>

              <div class="row user-row">
                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">

                  <% if @user_detail.profile_pic.exists? %>
                      <img alt="User Pic" src="<%=@user_detail.profile_pic.url%>" class="img-circle" width="50" height="50">
                  <%else%>
                      <img alt="User Pic" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=50" class="img-circle">
                  <%end%>

                </div>
                <div class="col-xs-8 col-sm-9 col-md-10 col-lg-10">
                  <strong> Name: <%=  @user_detail.first_name%> <%= @user_detail.last_name %> </strong><br>
                  <span class="text-muted"> Email: <%=  clients.email %>, Phone Number: <%= @user_detail.day_time_phone%> , Employer: <%= @user_detail.employer %> </span>
                </div>
                <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
                  <%= link_to '', new_lookbook_path(:type => clients.id), class: "glyphicon glyphicon-cloud-upload"  %>

                  <%= link_to '', edit_user_detail_path( :id  => @user_detail.id), class:"glyphicon glyphicon-edit"%>

                  <%= link_to 'View LookBooks', books_path( :id  =>  clients.id)%>

                </div>


              </div>


            </tr>
        <% end %>

        </thead>

        <tbody>

        </tbody>
      </table>





      <br>
      <%= link_to '', welcome_show_path, class: "glyphicon glyphicon-home"%>

    </div>

  </div>
</div>

app/views/follows/list_stylists.erb
<!--Number of followers of a user (Client) by different stylists-->

<br>
<h1 class="text-center login-title">List of Stylists (<%=current_user.follow_count%>) </h1>
<div class="container">
  <div class="well col-xs-8 col-sm-8 col-md-8 col-lg-8 col-xs-offset-2 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">
    <div class="row user-row">
      <table>
        <thead>

        <%  @user_list = current_user.all_following;


        %>

        <% @user_list.each do |stylists| %>
            <tr>

              <div class="row user-row">
                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">
                  <img class="img-circle"
                       src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=50"
                       alt="User Pic">
                </div>
                <div class="col-xs-8 col-sm-9 col-md-10 col-lg-10">
                  <strong> User ID: <%=  stylists.id %> </strong><br>
                  <!--<span class="text-muted"> Email: <%=   %> </span>-->
                </div>

              </div>


            </tr>
        <% end %>

        </thead>

        <tbody>

        </tbody>
      </table>





      <br>
      <%= link_to '', welcome_show_path, class: "glyphicon glyphicon-home"%>

    </div>

  </div>
</div>